name:                IOTasks-test-server
version:             0.1.0.0
github:              "owestphal/IOTasks-test-server"
license:             BSD3
author:              "Oliver Westphal"
copyright:           "2022 Oliver Westphal"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            backend server for demonstrating the Test.IOTasks library
category:            Web

description:         Please see the README on GitHub at <https://github.com/githubuser/server#readme>

dependencies:
- async
- base >= 4.7 && < 5
- bytestring
- directory
- ghc == 9.4.7
- ghc-paths
- IOTasks
- QuickCheck
- stm
- temporary
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-do-bind
- -Wno-name-shadowing
- -fdefer-typed-holes

executables:
  ghc-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    # - -threaded
    - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - IOTasks-test-server

library:
  source-dirs: src

tests:
  server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IOTasks-test-server
    - hspec
    - hspec-wai
