resolver: nightly-2023-06-20

packages:
- .

extra-deps:
- git: https://github.com/fmidue/IOTasks
  commit: fa460519053228b381206cc3835b32f7f3060be3
- git: https://github.com/IagoAbal/haskell-z3
  commit: b77a17e5eeb7db82656bcbcd66c6e952207e69ca
- git: https://github.com/owestphal/type-match
  commit: e5c0d104032d7e6ea147009669cbb95f3291b7bb

# system-ghc: true
