resolver: lts-21.19

packages:
- .

extra-deps:
- git: https://github.com/fmidue/IOTasks
  commit: 9115323eceaa93dd8345fc586c9d9a9b2b0a5f9c
- git: https://github.com/IagoAbal/haskell-z3
  commit: b77a17e5eeb7db82656bcbcd66c6e952207e69ca
- git: https://github.com/owestphal/type-match
  commit: 744797d33f85daa1d78181e2c512052903352dcc

# system-ghc: true
