resolver: lts-21.19

packages:
- .

extra-deps:
- git: https://github.com/fmidue/IOTasks
  commit: 34fcc46e76551ddd38a5432d4b4577d0f4c796cd
- git: https://github.com/IagoAbal/haskell-z3
  commit: b77a17e5eeb7db82656bcbcd66c6e952207e69ca
- git: https://github.com/owestphal/type-match
  commit: e1afab43d2e8bfa5e2006492ed34060036e7be51

# system-ghc: true
