resolver: lts-21.19

packages:
- .

extra-deps:
- git: https://github.com/fmidue/IOTasks
  commit: ddec953443a6af839bcce2c29f7664ca40e6167c
- git: https://github.com/IagoAbal/haskell-z3
  commit: b77a17e5eeb7db82656bcbcd66c6e952207e69ca
- git: https://github.com/owestphal/type-match
  commit: e1afab43d2e8bfa5e2006492ed34060036e7be51

# system-ghc: true
